Repository jphacks/E_2202, pull requests merged in 2022-11, with the labels that each got.

#82 Feature/#81 separate parse logic from main
  server/container_class.py
  server/main.py
  server/parser/__init__.py
  server/parser/other.py
  server/parser/python.py
Labels: Back End

#83 Feature/#75 add http cors
  .github/workflows/heroku-dev-backend.yml
  server/main.py
Labels: Back End

#87 #77 UIのリニューアル
  web/pages/index.tsx
  web/src/components/codeArea.tsx
  web/src/components/header.tsx
Labels: Front End

#90 Feature/#85 fix query builder
  web/pages/_document.tsx
  web/pages/index.tsx
Labels: ready for review, Front End

#89 同じ行に強調箇所が2箇所あった際のバグを修正
  web/src/components/codeArea.tsx
Labels: Front End

#93 fix filename url index bug
  server/parser/other.py
Labels: bug, Back End

#84 #15 Javaのエラーをパースする処理を追加した
  server/main.py
  server/parser/java.py
  web/pages/index.tsx
Labels: Back End

#94 Feature/#15 parse js error
  server/main.py
  server/parser/javascript.py
  web/pages/index.tsx
Labels: ready for review

#99 フォントを変更
  web/pages/_document.tsx
  web/src/components/codeArea.tsx
  web/src/theme.ts
Labels: ready for review, Front End

#103 #102 マスキング機能の追加
  web/pages/index.tsx
Labels: ready for review, Front End
