Repository jphacks/E_2202, pull requests merged in 2022-10, with the labels that each got.

#10 フロントの環境構築
  docker-compose.yml
  web/.eslintrc.json
  web/.gitignore
  web/README.md
  web/next.config.js
  web/package.json
  web/pages/_app.tsx
  web/pages/api/hello.ts
  web/pages/index.tsx
  web/public/favicon.ico
  web/public/vercel.svg
  web/styles/Home.module.css
  web/styles/globals.css
  web/tsconfig.json
  web/yarn.lock
Labels: ready for review

#11 バックエンドの環境構築
  docker-compose.yml
  server/.gitignore
  server/Dockerfile
  server/main.py
Labels: ready for review

#13 Feature/#3 parse error
  server/main.py
Labels: ready for review

#16 フロント画面の作成
  docker-compose.yml
  web/package-lock.json
  web/package.json
  web/pages/_app.tsx
  web/pages/_document.tsx
  web/pages/index.tsx
  web/pages/search.tsx
  web/src/createEmotionCache.ts
  web/src/theme.ts
  web/styles/Home.module.css
  web/styles/globals.css
  web/yarn.lock
Labels: ready for review

#20 Python用 Pre-Commitの設定
  server/Dockerfile
Labels: ready for review

#19 Feature/#17 build search query
  server/main.py
  web/pages/search.tsx
Labels: priority: high

#29 Feature/#28 本番環境用の設定に修正
  .github/workflows/heroku-deploy.yml
  server/main.py
  web/.env.development
  web/.env.production
  web/pages/index.tsx
Labels: ready for review

#27 error_parse APIのテスト作成
  server/Dockerfile
  server/main.py
  server/test_main.py
Labels: ready for review

#25 UnixファイルパスとURLの正規表現を作成した
  server/main.py
Labels: ready for review

#52 手元でCIと同じチェックを行うためにMakefileを追加
  Makefile
Labels: priority: low, Back End

#58 working_directoryの設定を追加
  .github/workflows/python-code-check.yml
  Makefile
  server/mypy.ini
Labels: ready for review, priority: low, Back End

#54 Pythonと他言語の解析処理を分ける
  server/main.py
  server/test_main.py
  web/pages/index.tsx
Labels: ready for review, Back End

#62 Feature/#45 add auto search function
  .github/workflows/heroku-dev-backend.yml
  .github/workflows/heroku-dev-frontend.yml
  web/pages/index.tsx
Labels: ready for review

#63 APIの返り値のテキストの重複除去処理を追加
  web/pages/index.tsx
Labels: ready for review, Front End

#67 URLとFILE PATHの除去処理を再度追加
  server/main.py
Labels: ready for review, priority: high, Back End

#50 Feature/#48 highlight error
  web/pages/codeAreaDemo.tsx
  web/pages/index.tsx
  web/src/components/codeArea.tsx
Labels: ready for review

#72 H1とページタイトルの修正
  web/pages/index.tsx
Labels: ready for review

#71 #70 Fix デプロイ先を変更
  .github/workflows/heroku-deploy-backend.yml
  .github/workflows/heroku-deploy.yml
  .github/workflows/heroku-dev-backend.yml
  .github/workflows/heroku-dev-frontend.yml
Labels: ready for review

#74 Feature/#73 uncontain libnames to query
  server/main.py
  web/pages/index.tsx
Labels: Front End
